name: Build DAPLink (Windows)
on:
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Cache Embedded Arm Toolchain
      id:   cache-arm-gcc
      uses: actions/cache@v2
      env:
        cache-name: arm-gcc-9-2020-q2
      with:
        path: ${{ runner.temp }}/arm-gcc
        key:  ${{ runner.os }}-${{ env.cache-name }}
        restore-keys: ${{ runner.os }}-${{ env.cache-name }}

    - name: Cache Python modules
      uses: actions/cache@v2
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Checkout source files
      uses: actions/checkout@v2

    - name: Install Embedded Arm Toolchain
      if:   steps.cache-arm-gcc.outputs.cache-hit != 'true'
      run:  |
        (New-Object System.Net.WebClient).DownloadFile("https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2020q2/gcc-arm-none-eabi-9-2020-q2-update-win32.zip","gcc-arm-none-eabi-9-2020-q2-update-win32.zip");
        echo "Installing gcc-arm-none-eabi-9-2020-q2-update-win32 in ${{ runner.temp }}\arm-gcc"
        Expand-Archive -Path .\gcc-arm-none-eabi-9-2020-q2-update-win32.zip -DestinationPath ${{ runner.temp }}\arm-gcc -PassThru;

    - name: Check Embedded Arm Toolchain
      run:  |
        echo ${{ runner.temp }}\arm-gcc\bin | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        ${{ runner.temp }}\arm-gcc\bin\arm-none-eabi-gcc -v

    - name: Install Python module
      run:  |
        pip install -r requirements.txt
        pip uninstall -y project-generator
        pip install -U git+https://github.com/mbrossard/project_generator.git@development

    - name: Compile
      run:  |
        python tools/progen_compile.py --release --parallel -v --ignore-
      shell: cmd

    - name: Upload test artifacts
      uses: actions/upload-artifact@v2
      with:
        name: firmware-dev-${{github.run_number}}
        path: |
          firmware*/*
          !firmware*/*.zip
